name: pull request

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syntax-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: make install
      - run: make awesome_lint
      - run: make export_markdown
